[package]
name = "permission"
version = "0.1.0"
authors = ["Denis Kolodin <deniskolodin@gmail.com>"]
repository = "https://github.com/DenisKolodin/permission"
description = "Generic permission control crate."

[dependencies]
